#!/bin/bash

echo ""
echo "╔═══════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                           ║"
echo "║          🚀 TRADING CONTROL PLATFORM - LAUNCH INSTRUCTIONS 🚀         ║"
echo "║                                                                           ║"
echo "║                    Combined TradeSniper + TradeZella                  ║"
echo "║                                                                           ║"
echo "╚═══════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Your platform is ready to launch!"
echo ""
echo "📋 GitHub Repository:"
echo "   👉 https://github.com/Abdihakim851/trading-control-platform"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🔧 STEP 1: Clone the Repository"
echo ""
echo "   git clone https://github.com/Abdihakim851/trading-control-platform.git"
echo "   cd trading-control-platform"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🗄️  STEP 2: Setup Database (Supabase - FREE)"
echo ""
echo "   1. Go to: https://app.supabase.com"
echo "   2. Click 'New Project'"
echo "   3. Create a project (choose region, set password)"
echo "   4. Wait for project to initialize (~2 minutes)"
echo "   5. Go to SQL Editor → New Query"
echo "   6. Copy content from: database/schema.sql"
echo "   7. Paste in SQL editor and click 'Run'"
echo ""
echo "✏️  Get Your Credentials:"
echo "   - Settings → API"
echo "   - Copy 'Project URL' → SUPABASE_URL"
echo "   - Copy 'anon public' → SUPABASE_ANON_KEY"
echo "   - Copy 'service_role' → SUPABASE_SERVICE_ROLE_KEY"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "⚙️  STEP 3: Setup Backend Environment"
echo ""
echo "   cd backend"
echo "   cp .env.example .env"
echo ""
echo "   Edit .env file and add your Supabase credentials:"
echo "   SUPABASE_URL=your_url"
echo "   SUPABASE_ANON_KEY=your_key"
echo "   SUPABASE_SERVICE_ROLE_KEY=your_key"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "⚙️  STEP 4: Setup Frontend Environment"
echo ""
echo "   cd ../frontend"
echo "   echo 'NEXT_PUBLIC_API_URL=http://localhost:5000/api' > .env.local"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 STEP 5: Install Dependencies & Start"
echo ""
echo "   Terminal 1 - Backend:"
echo "   ════════════════════════════════════════"
echo "   cd backend"
echo "   npm install"
echo "   npm run dev"
echo ""
echo "   Terminal 2 - Frontend:"
echo "   ════════════════════════════════════════"
echo "   cd frontend"
echo "   npm install"
echo "   npm run dev"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🌐 ACCESS YOUR PLATFORM"
echo ""
echo "   Frontend:    http://localhost:3000"
echo "   API Docs:    http://localhost:5000/api-docs"
echo "   Health:      http://localhost:5000/health"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "✨ FEATURES INCLUDED:"
echo ""
echo "   🎯 TradeSniper Features:"
echo "      • AI-Powered Chart Analysis"
echo "      • Order Block Detection"
echo "      • Confluence Point Identification"
echo "      • Liquidity Sweep Detection"
echo "      • Confidence Scoring (0-100%)"
echo ""
echo "   📊 TradeZella Features:"
echo "      • Advanced Trade Journaling"
echo "      • Performance Analytics Dashboard"
echo "      • Win Rate & P&L Tracking"
echo "      • Profit Factor Calculations"
echo "      • AI Insights & Recommendations"
echo "      • Backtesting Engine"
echo "      • Strategy Comparison"
echo "      • Mentorship System"
echo "      • Community Trading Spaces"
echo ""
echo "   🔧 Additional Features:"
echo "      • 500+ Broker Integration Support"
echo "      • Real-time Trade Syncing"
echo "      • User Authentication (JWT)"
echo "      • Responsive Mobile Design"
echo "      • Dark Mode UI"
echo "      • RESTful API with Swagger Docs"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTATION:"
echo ""
echo "   Main Guide:        See LAUNCH_GUIDE.md"
echo "   Setup Instructions: See SETUP.md"
echo "   Database Setup:    See database/README.md"
echo "   API Docs:          http://localhost:5000/api-docs (after running)"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🔐 DEFAULT TEST ACCOUNT (After Setup):"
echo ""
echo "   Email:    test@example.com"
echo "   Password: Test123!@#"
echo ""
echo "   (Create new accounts via /auth/register)"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 NOW GO LAUNCH IT!"
echo ""
echo "Questions? Check the documentation or GitHub Issues."
echo ""
echo "Happy Trading! 📈✨"
echo ""
echo ""
